<?php

/**
 * @file
 * Contains wn_realtime_seo.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for node_form().
 */
function wn_realtime_seo_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#after_build']) && !empty($form['#after_build'])) {
    $form['#after_build'][] = 'wn_realtime_seo_form_node_afterbuild';
  }
  else {
    $form['#after_build'] = ['wn_realtime_seo_form_node_afterbuild'];
  }
}

/**
 * After build function.
 *
 * Reads the form, and deduct associated yoastseo configuration from it.
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state array.
 *
 * @return mixed
 *   The modified form.
 */
function wn_realtime_seo_form_node_afterbuild($form, FormStateInterface $form_state) {
  if (isset($form['field_yoast_seo'])) {
    $realtime_seo_field_manager = \Drupal::service('wn_realtime_seo.field_manager');
    $form = $realtime_seo_field_manager->setFieldsConfiguration($form);
    $form = $realtime_seo_field_manager->addSnippetEditorMarkup($form);
  }

  return $form;
}
